# Generated by Django 6.0.6 on 2026-06-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
