# Generated by Django 6.0.6 on 2026-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='views',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], default='Available', max_length=10),
        ),
    ]
