# Generated by Django 6.0.6 on 2026-06-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_property_views_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
